CREATE DATABASE IF NOT EXISTS store;
USE store;

DROP TABLE IF EXISTS itemtocart;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS items;


CREATE TABLE carts (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NULL,
	capacity INT NULL DEFAULT NULL,
	UNIQUE(name),
	PRIMARY KEY(id)
);


CREATE TABLE items (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	description VARCHAR(100) NULL,
	price INT NULL,
    UNIQUE(name),
	PRIMARY KEY(id)
);


CREATE TABLE itemtocart (
	id INT NOT NULL AUTO_INCREMENT,
	cartid INT NOT NULL,
	itemid INT NOT NULL,
    FOREIGN KEY (cartid) REFERENCES carts(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (itemid) REFERENCES items(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(id),
    UNIQUE(cartid, itemid)
);
